### ISSUE TITLE
Some netrc parsers error if the file ownership or permissions are insecure

### ISSUE THREAD

**Issue by jpmckinney** [little-core-labs/netrc-creds#22]
For example, Python's [netrc module](https://docs.python.org/3/library/netrc.html). I think the file needs to not be readable except by the user.

**Comment by bcomnes** [comment]
Dang, picky parser!  Bug good catch.  Want to give a second pair of eyes on https://github.com/little-core-labs/netrc-creds/pull/23 ?

**Comment by bcomnes** [comment]
Try out v2.0.1

**Comment by jpmckinney** [comment]
It works!

https://github.com/open-contracting/standard/blob/1.1-dev/.github/workflows/ci.yml#L34-L41

**Comment by bcomnes** [comment]
Sweet.
